### ISSUE TITLE
Strategy to improve GA4 (google analytics) data analysis

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1241] opened 2024-04-15 20:37 UTC
We should see how [GTEx portal](https://support.terra.bio/attachments/token/rqaG2F5rSO1q9GPec5xnO2Frl/?name=CFDE+March+2024+Qiuyue+Liu+Poster.pdf) is doing and what we can learn from it.

**Comment by sujeetvkulkarni** [comment] 2024-04-16 17:09
Duplicate of #1167 .

**Closed as completed by sujeetvkulkarni** 2024-04-16 17:09 UTC
Labels: test phase
