### ISSUE TITLE
GGM.000252 is incorrect according to Mike

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#599] opened 2023-08-05 00:08 UTC
Mike said polysialic acid is something with two 2-8 connected Sialic acids.

**Comment by edwardsnj** [comment] 2023-08-16 14:49
As a motif, Mike is absolutely correct. This "motif" is not correct, but it (currently) doesn't match any false positive structures (and is simpler to compute with). I will try a repeat unit version of the motif and see how well it works...

**Comment by ReneRanzinger** [comment] 2023-08-16 16:19
Why repeating? Wouldnt the motif just consist of a di-saccharide with the linkage?

**Comment by edwardsnj** [comment] 2023-08-16 16:24
Ah, I see, I misunderstood. OK, got it. The original motif (specified with a repeating unit) described at least three. But happy to change it if Mike thinks a disaccharide sialic acid should qualify. This might result in more false positives (can't constrain to the non-reducing end without a repeat unit).

**Comment by ReneRanzinger** [comment] 2023-08-16 16:31
OK, I will add it to the agenda for next week to confirm the motif.

**Comment by edwardsnj** [comment] 2023-08-16 16:39
Here is the resulting set of aligned structures: 

  https://substructure.glyomics.org/?task_id=5d1fc6e27dc43610df2d1f9b491f513fd5122a78e28465a1ed86

There are some cases in there that probably look wrong (single NeuAc undetermined with non-specific placement, possible placement after a positioned NeuAc) where the intent is probably not to represent a double NeuAc, but that is what is implied by the structure sequence. Otherwise, all of the alignments are at the non-reducing end of the structures even though the motif does not constrain this.

**Comment by ReneRanzinger** [comment] 2023-08-16 16:56
Hi Mike,

In our last meeting with Mindy you identified that the current motif for poly sialic acid (https://glycomotif.glyomics.org/glycomotif/GGM.000252) is not correct. 

1. By your definition any structure that contains two (a2-8) linked sialic acids has the polysialic acid motif. Is that correct?

To make sure the updated motif will work properly, we also want to check some borderline cases with you:

2. Glycans that have unknown linkages (not a2-8) - https://glytoucan.org/Structures/Glycans/G64435UX . Would they still be considered poly sialic acid?

3. For uncertain terminal residue - https://glytoucan.org/Structures/Glycans/G98690XB . It could potentially mean that its two connection sialic acids (although in that case its unlikely). Should we annotate them with the motif or only structures that have explicit connections between two sialic acids (+ decision from 2.)? Example for the latter - https://glytoucan.org/Structures/Glycans/G99981ST

4. Are two other sialic acids besides Neu5Ac that are connected (+ decision from 2.) also considered poly sialic acids? E.g. Neu5Gc, Neu

5. What happens if one or both sialic acids have additional substituents - https://glytoucan.org/Structures/Glycans/G63043YQ? Are they still poly sialic acids? Like additional NAc, Ac, P ...

Hope you can clarify this,
   René

My opinion:
1. yes
2. no
3. no
4. good question
5. yes

**Comment by edwardsnj** [comment] 2023-08-16 17:52
Here is a "correct" representation of the poly Neu5Ac motif for my reference (with repeat unit). Note that 8-linkage is specified, but is not shown in the image the way it is drawn. 

Drawn structure: [Image](https://glymage.glyomics.org/getimage?notation=snfg&display=extended&format=png&seq=RES%0A1b%3Ab-dglc-HEX-1%3A5%0A2s%3An-acetyl%0A3b%3Ab-dgal-HEX-1%3A5%0A4b%3Aa-dgro-dgal-NON-2%3A6%7C1%3Aa%7C2%3Aketo%7C3%3Ad%0A5s%3An-acetyl%0A6r%3Ar1%0ALIN%0A1%3A1d(2%2B1)2n%0A2%3A1o(4%2B1)3d%0A3%3A3o(3%2B2)4d%0A4%3A4d(5%2B1)5n%0A5%3A4o(8%2B2)6n%0AREP%0AREP1%3A9o(8%2B2)9d%3D1-8%0ARES%0A9b%3Aa-dgro-dgal-NON-2%3A6%7C1%3Aa%7C2%3Aketo%7C3%3Ad%0A10s%3An-acetyl%0ALIN%0A8%3A9d(5%2B1)10n)

Substructure alignment is here: [Alignments](https://substructure.glyomics.org/?task_id=f9b653a910abb53f3557430da2d12f3dd5122a78e28465a1ed86)

(seems correct)

Nonreducing-end alignments don't seem to work (not sure why). 


```
RES
1b:b-dglc-HEX-1:5
2s:n-acetyl
3b:b-dgal-HEX-1:5
4b:a-dgro-dgal-NON-2:6|1:a|2:keto|3:d
5s:n-acetyl
6r:r1
LIN
1:1d(2+1)2n
2:1o(4+1)3d
3:3o(3+2)4d
4:4d(5+1)5n
5:4o(8+2)6n
REP
REP1:9o(8+2)9d=1-8
RES
9b:a-dgro-dgal-NON-2:6|1:a|2:keto|3:d
10s:n-acetyl
LIN
8:9d(5+1)10n
```

**Comment by edwardsnj** [comment] 2023-08-16 18:00
Rene's option 3 is essentially outside of the scope of the (current) logic of how motif alignment is carried out with respect to undetermined structures. The sequence definitively says the di-sialic-acid is one of the possible placements (even though we "known" that isn't what was intended), these are valid alignments. I don't want to have a "special" for specific motifs, it becomes untenable. I could implement a type/subtype (maybe we need the concept of a structure keyword?) that eliminated these (since subtype specific logic is often necessary). Or maybe we should have motif specific cleanup code. Ugh. Maybe?

**Comment by edwardsnj** [comment] 2023-09-12 16:44
I'm pushing this because there is more to figure out here. I don't think these edge cases (removing undetermined sialic acid marked as valid on the end of a salic acid) warrant a huge development push. There are a number of cases where the sloppy undetermined sequences conceptually describe impossible things. We do not eliminate these for other motifs, why this one? We should not *change* the definition of the sequence as provided. It is precise and clear (just likely not exactly what was intended).

**Comment by ReneRanzinger** [comment] 2023-09-12 19:23
I put it on the agenda for 9/13 so we can talk with @mtiemeyer0919 about it.

**Closed as completed** 2023-09-13 13:17 UTC
