### ISSUE TITLE
Provide glycan data for Nathan

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#470] opened 2023-07-04 19:53 UTC
Provided new glycan data as needed for Nathan. That may also include the Biomarker glycan data in case there are new structures.

**Blocker for**:
* #471 
* #473  
* #477

**Comment by kmartinez834** [comment] 2023-07-25 12:06
@edwardsnj Files have been downloaded and [Glycan File Tracker](https://docs.google.com/spreadsheets/d/1PYsMSfi5Z_6ZxHDMM8z5iSEXDOr6SAlzfpx01rWr0zc/edit?usp=sharing) updated with new yeast files:

- glyconnect_yeast.json
- yeast_o_glcnacome_mcw.csv
- yeast_protein_masterlist.csv (the link to ln2data won't work until we push the new release --> are you using these protein masterlist files?  If so, I will put a copy in an accessible folder so I don't have to email it to you)

**Comment by edwardsnj** [comment] 2023-07-25 20:23
I have switched to using glygen_protein_masterlist.csv with the hope that I don't have to continue to update it. I am only using the protein master lists to help assign taxids for unicarbkb data that has no species or no taxonomy id information. This file https://data.glygen.org/ln2downloads/glygen_protein_masterlist.csv does not seem to have yeast information in it. Should it?

**Comment by kmartinez834** [comment] 2023-07-27 07:11
Looks like Robel generated this file previously.  @rykahsay could you please reproduce for Nathan with all of the new protein masterlist files (including yeast)?
`/data/projects/glygen/downloads/glygen_protein_masterlist.csv`

**Comment by rykahsay** [comment] 2023-07-31 16:34
@kmartinez834 -- I thought I made a script for you to run every time we go for a release and I thought it was documented. Here is how you create that file (please document now).

```
cd /software/glygen
python dump_protein_masterlist.py
```

I have done this for now and the file is updated

**Comment by kmartinez834** [comment] 2023-07-31 18:40
Thanks @rykahsay , added to the documentation.

@edwardsnj https://data.glygen.org/ln2downloads/glygen_protein_masterlist.csv now contains yeast. Assigning to you, please close ticket once you confirm this is resolved.

**Closed as completed** 2023-09-21 17:49 UTC
